-- MySQL Schema for Streaming Platform
-- Converted from Oracle DDL

DROP DATABASE IF EXISTS streaming_platform;
CREATE DATABASE streaming_platform;
USE streaming_platform;

-- Production House Table
CREATE TABLE MSK_PROD_HOUSE (
    PRODUCTION_ID INT(7) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    STREET_ADDRESS VARCHAR(30),
    CITY VARCHAR(30),
    STATE VARCHAR(30),
    ZIP VARCHAR(15),
    DATE_ESTABLISHED DATE NOT NULL,
    INDEX idx_name (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Producer Table
CREATE TABLE MSK_PRODUCER (
    PRODUCER_ID VARCHAR(30) PRIMARY KEY,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30),
    STREET VARCHAR(30),
    CITY VARCHAR(30),
    STATE VARCHAR(30),
    ZIP INT(15),
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR(15),
    INDEX idx_email (EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Web Series Table
CREATE TABLE MSK_WEB_SERIES (
    SERIES_ID INT(7) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    NUMBER_OF_EPISODES INT(6),
    RELEASE_DATE DATE,
    COUNTRY_OF_RELEASE VARCHAR(30) NOT NULL,
    POSTER_URL VARCHAR(255),
    BANNER_URL VARCHAR(255),
    DESCRIPTION TEXT,
    CONSTRAINT CHK_NUMBER_OF_EPISODES CHECK (NUMBER_OF_EPISODES > 0),
    INDEX idx_name (NAME),
    INDEX idx_release_date (RELEASE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Contracts Table
CREATE TABLE MSK_CONTRACTS (
    CONTRACT_ID INT(7) AUTO_INCREMENT PRIMARY KEY,
    PROD_HOUSE_ID INT(7) NOT NULL,
    SERIES_ID INT(7) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    RATE_PER_EPISODE DECIMAL(10,2) NOT NULL,
    IS_RENEWED CHAR(1) DEFAULT 'N',
    CONSTRAINT CHK_CONTRACT_DATES CHECK (END_DATE > START_DATE),
    CONSTRAINT CHK_RATE_PER_EPISODE CHECK (RATE_PER_EPISODE > 0),
    CONSTRAINT CHK_IS_RENEWED CHECK (IS_RENEWED IN ('Y', 'N')),
    FOREIGN KEY (PROD_HOUSE_ID) REFERENCES MSK_PROD_HOUSE(PRODUCTION_ID) ON DELETE CASCADE,
    FOREIGN KEY (SERIES_ID) REFERENCES MSK_WEB_SERIES(SERIES_ID) ON DELETE CASCADE,
    INDEX idx_series (SERIES_ID),
    INDEX idx_prod_house (PROD_HOUSE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Country Table
CREATE TABLE MSK_COUNTRY (
    COUNTRY_ID INT(7) AUTO_INCREMENT PRIMARY KEY,
    SERIES_ID INT(7) NOT NULL,
    PRODUCER_ID VARCHAR(30) NOT NULL,
    COUNTRY_NAME VARCHAR(50) NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES MSK_WEB_SERIES(SERIES_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCER_ID) REFERENCES MSK_PRODUCER(PRODUCER_ID) ON DELETE CASCADE,
    INDEX idx_series (SERIES_ID),
    INDEX idx_producer (PRODUCER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Episode Table
CREATE TABLE MSK_EPISODE (
    EPISODE_ID INT(7) AUTO_INCREMENT,
    SERIES_ID INT(7) NOT NULL,
    EPISODE_NO INT(5) NOT NULL,
    EPISODE_TITLE VARCHAR(50),
    DURATION_MIN INT(5),
    VIEWERS INT(10) DEFAULT 0,
    TECH_INTERRUPTION CHAR(1) NOT NULL DEFAULT 'N',
    VIDEO_URL VARCHAR(255),
    THUMBNAIL_URL VARCHAR(255),
    PRIMARY KEY (EPISODE_ID, SERIES_ID),
    CONSTRAINT CHK_EPISODE_NUMBER CHECK (EPISODE_NO > 0),
    CONSTRAINT CHK_DURATION_MINUTES CHECK (DURATION_MIN > 0),
    CONSTRAINT CHK_VIEWERS_POSITIVE CHECK (VIEWERS >= 0),
    CONSTRAINT CHK_TECH_INTERRUPTION CHECK (TECH_INTERRUPTION IN ('Y', 'N')),
    FOREIGN KEY (SERIES_ID) REFERENCES MSK_WEB_SERIES(SERIES_ID) ON DELETE CASCADE,
    INDEX idx_series (SERIES_ID),
    INDEX idx_episode_no (EPISODE_NO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Schedule Table
CREATE TABLE MSK_SCHEDULE (
    SCHEDULE_ID INT(7) AUTO_INCREMENT PRIMARY KEY,
    EPISODE_ID INT(7) NOT NULL,
    SERIES_ID INT(7) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    IS_CURRENT CHAR(1) NOT NULL DEFAULT 'N',
    FOREIGN KEY (EPISODE_ID, SERIES_ID) REFERENCES MSK_EPISODE(EPISODE_ID, SERIES_ID) ON DELETE CASCADE,
    INDEX idx_episode (EPISODE_ID, SERIES_ID),
    INDEX idx_current (IS_CURRENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Series Type Table
CREATE TABLE MSK_SERIES_TYPE (
    TYPE_NAME VARCHAR(50) NOT NULL,
    SERIES_ID INT(7) NOT NULL,
    PRIMARY KEY (TYPE_NAME, SERIES_ID),
    FOREIGN KEY (SERIES_ID) REFERENCES MSK_WEB_SERIES(SERIES_ID) ON DELETE CASCADE,
    INDEX idx_series (SERIES_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Series Dubbing Table
CREATE TABLE MSK_SERIES_DUBBING (
    DUBBING_ID INT(7) AUTO_INCREMENT PRIMARY KEY,
    SERIES_ID INT(7) NOT NULL,
    DUBBING_LANGUAGE VARCHAR(30),
    FOREIGN KEY (SERIES_ID) REFERENCES MSK_WEB_SERIES(SERIES_ID) ON DELETE CASCADE,
    INDEX idx_series (SERIES_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Series Subtitle Table
CREATE TABLE MSK_SERIES_SUBTITLE (
    SUBTITLE_ID INT(7) AUTO_INCREMENT PRIMARY KEY,
    SERIES_ID INT(7) NOT NULL,
    SUBTITLE_LANGUAGE VARCHAR(30) NOT NULL,
    FOREIGN KEY (SERIES_ID) REFERENCES MSK_WEB_SERIES(SERIES_ID) ON DELETE CASCADE,
    INDEX idx_series (SERIES_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Prod-Prod House Junction Table
CREATE TABLE MSK_PROD_PROD_HOUSE (
    PRODUCER_ID VARCHAR(30) NOT NULL,
    PROD_HOUSE_ID INT(7) NOT NULL,
    PRIMARY KEY (PRODUCER_ID, PROD_HOUSE_ID),
    FOREIGN KEY (PRODUCER_ID) REFERENCES MSK_PRODUCER(PRODUCER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PROD_HOUSE_ID) REFERENCES MSK_PROD_HOUSE(PRODUCTION_ID) ON DELETE CASCADE,
    INDEX idx_producer (PRODUCER_ID),
    INDEX idx_prod_house (PROD_HOUSE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Viewer Table
CREATE TABLE MSK_VIEWER (
    VIEWER_ID INT(7) AUTO_INCREMENT PRIMARY KEY,
    SERIES_ID INT(7) NOT NULL,
    COUNTRY_ID INT(7) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30),
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    BILLING_STREET VARCHAR(50),
    BILLING_CITY VARCHAR(30),
    BILLING_ZIPCODE INT(10),
    MONTHLY_FEE DECIMAL(5,2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CHK_MONTHLY_FEE CHECK (MONTHLY_FEE > 0),
    FOREIGN KEY (SERIES_ID) REFERENCES MSK_WEB_SERIES(SERIES_ID) ON DELETE CASCADE,
    FOREIGN KEY (COUNTRY_ID) REFERENCES MSK_COUNTRY(COUNTRY_ID) ON DELETE CASCADE,
    INDEX idx_email (EMAIL),
    INDEX idx_series (SERIES_ID),
    INDEX idx_country (COUNTRY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Feedback Table
CREATE TABLE MSK_FEEDBACK (
    FEEDBACK_ID INT(7) AUTO_INCREMENT PRIMARY KEY,
    VIEWER_ID INT(7) NOT NULL,
    SERIES_ID INT(7) NOT NULL,
    RATING DECIMAL(2,1),
    DATE DATE NOT NULL,
    TEXT VARCHAR(2000),
    CONSTRAINT CHK_RATING_RANGE CHECK (RATING BETWEEN 1 AND 5),
    FOREIGN KEY (VIEWER_ID) REFERENCES MSK_VIEWER(VIEWER_ID) ON DELETE CASCADE,
    FOREIGN KEY (SERIES_ID) REFERENCES MSK_WEB_SERIES(SERIES_ID) ON DELETE CASCADE,
    INDEX idx_viewer (VIEWER_ID),
    INDEX idx_series (SERIES_ID),
    INDEX idx_rating (RATING)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Watch History Table (for Apple TV-like continue watching)
CREATE TABLE MSK_WATCH_HISTORY (
    HISTORY_ID INT(7) AUTO_INCREMENT PRIMARY KEY,
    VIEWER_ID INT(7) NOT NULL,
    EPISODE_ID INT(7) NOT NULL,
    SERIES_ID INT(7) NOT NULL,
    WATCH_PROGRESS INT(5) DEFAULT 0,
    LAST_WATCHED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (VIEWER_ID) REFERENCES MSK_VIEWER(VIEWER_ID) ON DELETE CASCADE,
    FOREIGN KEY (EPISODE_ID, SERIES_ID) REFERENCES MSK_EPISODE(EPISODE_ID, SERIES_ID) ON DELETE CASCADE,
    INDEX idx_viewer (VIEWER_ID),
    INDEX idx_episode (EPISODE_ID, SERIES_ID),
    INDEX idx_last_watched (LAST_WATCHED)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
